version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache
    volumes:
      - ../librairie:/var/www/html/librairie
    ports:
      - '8080:80'
    depends_on:
      - db
    env_file:
      - .env
    command: >
      sh -c "apache2-foreground"

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library
      MYSQL_USER: library_user
      MYSQL_PASSWORD: library_password
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '8081:80'
    depends_on:
      - db

volumes:
  db_data:
